x-common: &common
  restart: unless-stopped
  logging:
    options:
      max-size: 50m
      max-file: "3"

x-clickhouse-defaults: &clickhouse-defaults
  !!merge <<: *common
  image: clickhouse/clickhouse-server:25.5.6
  tty: true
  depends_on:
    init-clickhouse:
      condition: service_completed_successfully
    zookeeper-1:
      condition: service_healthy
  healthcheck:
    test:
      - CMD
      - wget
      - --spider
      - -q
      - 0.0.0.0:8123/ping
    interval: 30s
    timeout: 5s
    retries: 3
  ulimits:
    nproc: 65535
    nofile:
      soft: 262144
      hard: 262144
  environment:
    - CLICKHOUSE_SKIP_USER_SETUP=1

x-db-depend: &db-depend
  !!merge <<: *common
  depends_on:
    clickhouse:
      condition: service_healthy

name: infrastructure
services:
  # ---------------------------------------------------------------------------
  # SigNoz observability stack
  # ---------------------------------------------------------------------------
  init-clickhouse:
    !!merge <<: *common
    image: clickhouse/clickhouse-server:25.5.6
    container_name: signoz-init-clickhouse
    command:
      - bash
      - -c
      - |
        version="v0.0.1"
        node_os=$$(uname -s | tr '[:upper:]' '[:lower:]')
        node_arch=$$(uname -m | sed s/aarch64/arm64/ | sed s/x86_64/amd64/)
        echo "Fetching histogram-binary for $${node_os}/$${node_arch}"
        cd /tmp
        wget -O histogram-quantile.tar.gz "https://github.com/SigNoz/signoz/releases/download/histogram-quantile%2F$${version}/histogram-quantile_$${node_os}_$${node_arch}.tar.gz"
        tar -xvzf histogram-quantile.tar.gz
        mv histogram-quantile /var/lib/clickhouse/user_scripts/histogramQuantile
    restart: on-failure
    volumes:
      - clickhouse-user-scripts:/var/lib/clickhouse/user_scripts/
    networks:
      - infrastructure

  zookeeper-1:
    !!merge <<: *common
    image: signoz/zookeeper:3.7.1
    container_name: signoz-zookeeper-1
    user: root
    healthcheck:
      test:
        - CMD-SHELL
        - curl -s -m 2 http://localhost:8080/commands/ruok | grep error | grep null
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - zookeeper-1:/bitnami/zookeeper
    environment:
      - ZOO_SERVER_ID=1
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_AUTOPURGE_INTERVAL=1
      - ZOO_ENABLE_PROMETHEUS_METRICS=yes
      - ZOO_PROMETHEUS_METRICS_PORT_NUMBER=9141
    networks:
      - infrastructure

  clickhouse:
    !!merge <<: *clickhouse-defaults
    container_name: signoz-clickhouse
    volumes:
      - ${CONFIG_DIR:-./config}/clickhouse/config.xml:/etc/clickhouse-server/config.xml
      - ${CONFIG_DIR:-./config}/clickhouse/users.xml:/etc/clickhouse-server/users.xml
      - ${CONFIG_DIR:-./config}/clickhouse/custom-function.xml:/etc/clickhouse-server/custom-function.xml
      - clickhouse-user-scripts:/var/lib/clickhouse/user_scripts/
      - ${CONFIG_DIR:-./config}/clickhouse/cluster.xml:/etc/clickhouse-server/config.d/cluster.xml
      - clickhouse:/var/lib/clickhouse/
    networks:
      - infrastructure

  signoz:
    !!merge <<: *db-depend
    image: signoz/signoz:v0.114.1
    container_name: signoz
    ports:
      - "3301:8080" # SigNoz UI
    volumes:
      - signoz-sqlite:/var/lib/signoz/
    environment:
      - SIGNOZ_ALERTMANAGER_PROVIDER=signoz
      - SIGNOZ_TELEMETRYSTORE_CLICKHOUSE_DSN=tcp://clickhouse:9000
      - SIGNOZ_SQLSTORE_SQLITE_PATH=/var/lib/signoz/signoz.db
      - SIGNOZ_TOKENIZER_JWT_SECRET=secret
      - SIGNOZ_USER_ROOT_EMAIL=demeyerthom@gmail.com
      - SIGNOZ_USER_ROOT_PASSWORD=signoz
    healthcheck:
      test:
        - CMD
        - wget
        - --spider
        - -q
        - localhost:8080/api/v1/health
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - infrastructure

  signoz-telemetrystore-migrator:
    !!merge <<: *db-depend
    image: signoz/signoz-otel-collector:v0.144.2
    container_name: signoz-telemetrystore-migrator
    environment:
      - SIGNOZ_OTEL_COLLECTOR_CLICKHOUSE_DSN=tcp://clickhouse:9000
      - SIGNOZ_OTEL_COLLECTOR_CLICKHOUSE_CLUSTER=cluster
      - SIGNOZ_OTEL_COLLECTOR_CLICKHOUSE_REPLICATION=true
      - SIGNOZ_OTEL_COLLECTOR_TIMEOUT=10m
    entrypoint:
      - /bin/sh
    command:
      - -c
      - |
        /signoz-otel-collector migrate bootstrap &&
        /signoz-otel-collector migrate sync up &&
        /signoz-otel-collector migrate async up
    restart: on-failure
    networks:
      - infrastructure

  otel-collector:
    !!merge <<: *db-depend
    image: signoz/signoz-otel-collector:v0.144.2
    container_name: otel-collector
    entrypoint:
      - /bin/sh
    command:
      - -c
      - |
        /signoz-otel-collector migrate sync check &&
        /signoz-otel-collector --config=/etc/otel-collector-config.yaml --manager-config=/etc/manager-config.yaml --copy-path=/var/tmp/collector-config.yaml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CONFIG_DIR:-./config}/otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ${CONFIG_DIR:-./config}/signoz/otel-collector-opamp-config.yaml:/etc/manager-config.yaml
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=host.name=infrastructure-host,os.type=linux
      - LOW_CARDINAL_EXCEPTION_GROUPING=false
      - SIGNOZ_OTEL_COLLECTOR_CLICKHOUSE_DSN=tcp://clickhouse:9000
      - SIGNOZ_OTEL_COLLECTOR_CLICKHOUSE_CLUSTER=cluster
      - SIGNOZ_OTEL_COLLECTOR_CLICKHOUSE_REPLICATION=true
      - SIGNOZ_OTEL_COLLECTOR_TIMEOUT=10m
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the Collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
    networks:
      - infrastructure

  # ---------------------------------------------------------------------------
  # Infrastructure services
  # ---------------------------------------------------------------------------
  redis:
    !!merge <<: *common
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - infrastructure

  mongodb:
    !!merge <<: *common
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ${DATA_DIR:-./data}/mongodb:/data/db
    networks:
      - infrastructure

  traefik:
    !!merge <<: *common
    container_name: traefik
    image: traefik:v3.6.4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CONFIG_DIR:-./config}/traefik/traefik.yaml:/traefik.yml
    ports:
      - "80:80"
      - "443:443"
      - "9000:9000"
    networks:
      - infrastructure

  elasticsearch:
    !!merge <<: *common
    container_name: elasticsearch
    environment:
      - cluster.routing.allocation.disk.threshold_enabled=true
      - cluster.routing.allocation.disk.watermark.low=512mb
      - cluster.routing.allocation.disk.watermark.high=256mb
      - cluster.routing.allocation.disk.watermark.flood_stage=128mb
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - xpack.security.enabled=false
    image: elasticsearch:7.17.27
    ports:
      - "9200:9200"
    volumes:
      - ${DATA_DIR:-./data}/elasticsearch:/var/lib/elasticsearch/data
    networks:
      - infrastructure

  postgresql:
    !!merge <<: *common
    container_name: postgresql
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - ${DATA_DIR:-./data}/postgresql:/var/lib/postgresql/data
    networks:
      - infrastructure

  temporal:
    !!merge <<: *common
    container_name: temporal
    image: temporalio/auto-setup:1.29.1
    depends_on:
      - postgresql
      - elasticsearch
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
      - ENABLE_ES=true
      - ES_SEEDS=elasticsearch
      - ES_VERSION=v7
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    ports:
      - "7233:7233"
    networks:
      - infrastructure

  temporal-ui:
    !!merge <<: *common
    container_name: temporal-ui
    image: temporalio/ui:2.34.0
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_UNSAFE_ALLOW_ALL_ORIGINS=true
    ports:
      - "8080:8080"
    networks:
      - infrastructure

  ollama:
    !!merge <<: *common
    container_name: ollama
    build:
      context: .
      dockerfile: ./docker/ollama/Dockerfile
    ports:
      - "11434:11434"
    networks:
      - infrastructure

  # n8n:
  #   !!merge <<: *common
  #   container_name: n8n
  #   image: n8nio/n8n:2.9.4
  #   environment:
  #     - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
  #     - N8N_RUNNERS_ENABLED=admin
  #   ports:
  #     - "5678:5678"
  #   networks:
  #     - infrastructure

networks:
  infrastructure:
    name: infrastructure
    driver: bridge

volumes:
  clickhouse:
    name: signoz-clickhouse
  clickhouse-user-scripts:
    name: signoz-clickhouse-user-scripts
  signoz-sqlite:
    name: signoz-sqlite
  zookeeper-1:
    name: signoz-zookeeper-1
