version: "3"

includes:
  edge-proxy:
    taskfile: ./edge-proxy/Taskfile.yml
    dir: ./edge-proxy
  forgejo:
    taskfile: ./forgejo/Taskfile.yml
    dir: ./forgejo
  signoz:
    taskfile: ./signoz/Taskfile.yml
    dir: ./signoz

tasks:
  default:
    cmd: task --list
