x-common: &common
  restart: unless-stopped
  logging:
    options:
      max-size: 50m
      max-file: "3"

name: freshrss
services:
  freshrss:
    <<: *common
    image: freshrss/freshrss:1.29.1
    container_name: freshrss
    environment:
      - TZ=Europe/Amsterdam
      - CRON_MIN=13,43
      - FRESHRSS_ENV=production
      - LISTEN=0.0.0.0:80
      - TRUSTED_PROXY=192.168.1.42
      - FRESHRSS_INSTALL=--api-enabled --base-url https://feeds.de-meyer.nl --db-type sqlite --default-user admin --language en
      - FRESHRSS_USER=--user admin --password ${ADMIN_PASSWORD} --api-password ${ADMIN_API_PASSWORD} --email ${ADMIN_EMAIL} --language en
    command:
      - /bin/bash
      - -c
      - |
        sed -i "s/'is_admin' => false/'is_admin' => true/" /var/www/FreshRSS/data/users/admin/config.php 2>/dev/null || true
        ([ -z "$$CRON_MIN" ] || cron) && . /etc/apache2/envvars && exec apache2 -D FOREGROUND $$([ -n "$$OIDC_ENABLED" ] && [ "$$OIDC_ENABLED" -ne 0 ] && echo "-D OIDC_ENABLED")
    volumes:
      - ${DATA_DIR:-./data}/freshrss:/var/www/FreshRSS/data
      - ${CONFIG_DIR:-./config}/freshrss:/var/www/FreshRSS/extensions
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8080:80"
    networks:
      - freshrss
    deploy:
      resources:
        limits:
          memory: 512m
    healthcheck:
      test: ["CMD", "cli/health.php"]
      timeout: 10s
      start_period: 60s
      start_interval: 11s
      interval: 75s
      retries: 3

networks:
  freshrss:
    name: freshrss
    external: true
