version: "3"

tasks:
  deploy:
    desc: Deploy Temporal to CT 116
    cmds:
      - docker --context temporal compose --env-file .env.remote -f docker-compose.yaml up -d --build --remove-orphans

  clean:
    desc: Clean up temporal stack
    cmds:
      - docker --context temporal compose --env-file .env.remote -f docker-compose.yaml rm -v -f
